/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Helpdesk.view.MainView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.mainview',

    requires: [
        'Helpdesk.view.TicketList',
        'Ext.dataview.List',
        'Ext.navigation.Bar',
        'Ext.Button'
    ],

    config: {
        itemId: 'mynavigationview',
        items: [
            {
                xtype: 'ticketlist',
                title: 'Your tickets'
            }
        ],
        navigationBar: {
            docked: 'top',
            items: [
                {
                    xtype: 'button',
                    align: 'right',
                    itemId: 'mybutton6',
                    iconCls: 'fa-bars'
                }
            ]
        },
        listeners: [
            {
                fn: 'onMybutton6Tap',
                event: 'tap',
                delegate: '#mybutton6'
            }
        ]
    },

    onMybutton6Tap: function(button, e, eOpts) {
        Ext.Viewport.toggleMenu('right');
    }

});