/*
 * File: app/view/TicketList.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Helpdesk.view.TicketList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.ticketlist',

    requires: [
        'Ext.XTemplate',
        'Ext.plugin.PullRefresh',
        'Ext.Toolbar',
        'Ext.Spacer',
        'Ext.Button'
    ],

    config: {
        disableSelection: true,
        store: 'Tickets',
        grouped: true,
        itemTpl: [
            '<div>{Title}</div>',
            '<div class="listDates">',
            '    <div>Created on {DateCreated:date(\'d/m/Y\')}</div>',
            '    <tpl if="Closed == true">',
            '        <div>Closed on {DateClosed:date(\'d/m/Y\')}</div>',
            '    </tpl>',
            '</div>'
        ],
        plugins: [
            {
                type: 'pullrefresh'
            }
        ],
        items: [
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        iconCls: 'fa-plus',
                        text: 'New Ticket'
                    }
                ]
            }
        ]
    }

});